# 本机使用时的样例配置文件
port: 48091                     # 服务器端口
host: "0.0.0.0"               # 监听地址
openBrowser: false              # 启动完成后自动打开浏览器（Electron环境下关闭）
allowBroadcastToClients: true   # 允许向所有已连接的客户端广播消息
enableAccessLogger: false       # 是否启用访问日志记录